# Font
font_family Comfortaa

# Copy/Paste
paste_actions confirm

# Scroll
scrollback_lines 10000

# Bell
enable_audio_bell no
visual_bell_duration 0.5 ease-in-out linear
visual_bell_color #708090

# Background
background_opacity 0.9

# Cursor 
cursor_blink_interval 2 ease-in-out
cursor_trail 1
cursor_trail_decay 0.03 0.2

# Tabs
active_tab_font_style bold
tab_bar_style powerline 
tab_powerline_style slanted
